# Generated by Django 6.0.3 on 2026-03-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['name'], name='branches_br_name_820a7c_idx'),
        ),
    ]
