# Generated by Django 6.0.3 on 2026-04-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='', help_text='Filename only e.g. fanta.png — file must exist in static/images/', max_length=100),
        ),
    ]
