# Generated by Django 6.0.3 on 2026-03-12 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_branch_branches_br_name_820a7c_idx'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_sold', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='products.product')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_d_date_267a38_idx'), models.Index(fields=['branch', 'date'], name='analytics_d_branch__f35f86_idx'), models.Index(fields=['product', 'date'], name='analytics_d_product_817728_idx'), models.Index(fields=['branch', 'product', 'date'], name='analytics_d_branch__3a49b6_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'product', 'date'), name='unique_daily_report')],
            },
        ),
        migrations.CreateModel(
            name='MonthlySalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_sold', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_reports', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_reports', to='products.product')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['year', 'month'], name='analytics_m_year_77d4e4_idx'), models.Index(fields=['branch', 'year', 'month'], name='analytics_m_branch__51bdea_idx'), models.Index(fields=['product', 'year', 'month'], name='analytics_m_product_7195e7_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'product', 'year', 'month'), name='unique_monthly_report')],
            },
        ),
    ]
