# Generated by Django 6.0.3 on 2026-03-12 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_branch_branches_br_name_820a7c_idx'),
        ('inventory', '0002_restocklog'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_at_alert', models.PositiveIntegerField()),
                ('threshold', models.PositiveIntegerField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='branches.branch')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='products.product')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_resolved'], name='alerts_stoc_is_reso_743be4_idx'), models.Index(fields=['branch', 'is_resolved'], name='alerts_stoc_branch__669717_idx'), models.Index(fields=['product', 'is_resolved'], name='alerts_stoc_product_17c721_idx'), models.Index(fields=['created_at'], name='alerts_stoc_created_03c200_idx')],
            },
        ),
    ]
