# Generated by Django 6.0.3 on 2026-03-11 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'indexes': [models.Index(fields=['branch', 'product'], name='inventory_i_branch__8d46f4_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'product'), name='unique_branch_product_inventory')],
            },
        ),
    ]
