# Generated by Django 6.0.3 on 2026-03-12 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.PositiveIntegerField()),
                ('stock_before', models.PositiveIntegerField()),
                ('stock_after', models.PositiveIntegerField()),
                ('restocked_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restock_logs', to='inventory.inventory')),
                ('restocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restock_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-restocked_at'],
                'indexes': [models.Index(fields=['restocked_at'], name='inventory_r_restock_ccf30a_idx'), models.Index(fields=['inventory', 'restocked_at'], name='inventory_r_invento_eab9ce_idx')],
            },
        ),
    ]
