# Generated by Django 6.0.3 on 2026-04-24 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_restocklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1, message='Low stock threshold must be at least 1.')]),
        ),
    ]
