# Generated by Django 6.0.3 on 2026-03-13 11:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits starting with 07 or 01.', regex='^(07|01)\\d{8}$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checkout_request_id', models.CharField(blank=True, help_text='M-Pesa STK push identifier', max_length=100, null=True, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, help_text='M-Pesa merchant request identifier', max_length=100, null=True)),
                ('receipt_number', models.CharField(blank=True, help_text='M-Pesa receipt number after successful payment', max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=10)),
                ('raw_callback', models.JSONField(blank=True, help_text='Raw M-Pesa callback response for debugging', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Safaricom failure description for failed payments', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['checkout_request_id'], name='payments_pa_checkou_e4cf10_idx'), models.Index(fields=['receipt_number'], name='payments_pa_receipt_1332c1_idx'), models.Index(fields=['created_at'], name='payments_pa_created_b8a300_idx')],
            },
        ),
    ]
